---
services:
  php-apache:
    container_name: "${CONTAINER_NAME_PREFIX}-apache-php"
    depends_on:
      db:
        condition: service_healthy
    build: ./php-apache
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - APP_SECRET=${APP_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - HABITAT_DOMAIN=${HABITAT_DOMAIN}
    volumes:
      - ${PATH_TO_SYMFONY_PROJECT}:/var/www/html
    ports:
      - "80:80"

  db:
    container_name: "${CONTAINER_NAME_PREFIX}-mariadb"
    image: mariadb:latest
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MARIADB_ROOT_USER=${ROOT_USER}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - ${PATH_TO_DB_DATA}:/var/lib/mysql:rw
    ports:
      - "3306:3306"

  mailer:
    container_name: "${CONTAINER_NAME_PREFIX}-mailer"
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
