---
# TODO: Put this into the Github CI
#
# docker system prune -a
# docker compose -f compose.yaml -f compose.prod.yaml build --pull --no-cache
#
# docker tag carlnewton/habitat carlnewton/habitat:1.2.3-rc1
# docker push carlnewton/habitat:1.2.3-rc1
#
# docker tag carlnewton/habitat carlnewton/habitat:1.2.3
# docker push carlnewton/habitat:1.2.3
#
# docker tag carlnewton/habitat carlnewton/habitat:latest
# docker push carlnewton/habitat:latest
services:
  habitat-app:
    build:
      context: .
      target: frankenphp_prod
    image: carlnewton/habitat
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  habitat-worker:
    extends:
      file: compose.yaml
      service: habitat-worker
    image: ${IMAGES_PREFIX:-}app-php-worker
    build:
      context: .
      target: frankenphp_prod
    command: ['bin/console', 'messenger:consume', '-vv', '--time-limit=600', '--limit=10', '--memory-limit=128M']
    volumes:
      - ./:/app
      - /app/var/
      - habitat_uploads:/uploads
    depends_on:
      habitat-app:
        condition: service_healthy
