<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251230185814 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE announcement (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              content TEXT DEFAULT NULL,
              show_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              hide_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              type SMALLINT NOT NULL,
              title VARCHAR(255) DEFAULT NULL,
              collapse BOOLEAN NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE blocked_email_address (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email_address VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE category (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              description TEXT DEFAULT NULL,
              location SMALLINT NOT NULL,
              allow_posting BOOLEAN NOT NULL,
              weight INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE comment (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              body TEXT NOT NULL,
              posted TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id INT NOT NULL,
              post_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_9474526CA76ED395 ON comment (user_id)');
        $this->addSql('CREATE INDEX IDX_9474526C4B89032C ON comment (post_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE heart (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              user_id INT NOT NULL,
              post_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_60ECC3E6A76ED395 ON heart (user_id)');
        $this->addSql('CREATE INDEX IDX_60ECC3E64B89032C ON heart (post_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE moderation_log (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              action TEXT NOT NULL,
              user_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_7AE8684DA76ED395 ON moderation_log (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE notification (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              type SMALLINT NOT NULL,
              date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              data JSON DEFAULT NULL,
              user_id INT NOT NULL,
              post_id INT DEFAULT NULL,
              comment_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA4B89032C ON notification (post_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAF8697D13 ON notification (comment_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE post (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              title VARCHAR(255) NOT NULL,
              body TEXT DEFAULT NULL,
              posted TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              latitude DOUBLE PRECISION DEFAULT NULL,
              longitude DOUBLE PRECISION DEFAULT NULL,
              user_id INT NOT NULL,
              category_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_5A8A6C8DA76ED395 ON post (user_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D12469DE2 ON post (category_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE post_attachment (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              filename VARCHAR(255) NOT NULL,
              width SMALLINT NOT NULL,
              height SMALLINT NOT NULL,
              post_id INT DEFAULT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_5A27D07A4B89032C ON post_attachment (post_id)');
        $this->addSql('CREATE INDEX IDX_5A27D07AA76ED395 ON post_attachment (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE registration_question (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              question VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE registration_question_answer (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              answer VARCHAR(255) NOT NULL,
              question_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_58C2CB1B1E27F6BF ON registration_question_answer (question_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE report (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              reported_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              reason TEXT DEFAULT NULL,
              type VARCHAR(255) NOT NULL,
              reported_by_id INT NOT NULL,
              post_id INT DEFAULT NULL,
              comment_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_C42F778471CE806 ON report (reported_by_id)');
        $this->addSql('CREATE INDEX IDX_C42F77844B89032C ON report (post_id)');
        $this->addSql('CREATE INDEX IDX_C42F7784F8697D13 ON report (comment_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE settings (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              value VARCHAR(255) DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE sidebar_content (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              content TEXT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE EXTENSION IF NOT EXISTS citext;
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              username CITEXT NOT NULL,
              roles JSONB DEFAULT NULL,
              password VARCHAR(255) NOT NULL,
              email_address VARCHAR(255) NOT NULL,
              created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              email_verified BOOLEAN NOT NULL,
              email_verification_string VARCHAR(32) DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql(<<<'SQL'
            CREATE TABLE user_freeze_log (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              freeze_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              unfreeze_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              reason VARCHAR(255) NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_1FBF84DAA76ED395 ON user_freeze_log (user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE user_hidden_category (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              user_id INT NOT NULL,
              category_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_AF05376CA76ED395 ON user_hidden_category (user_id)');
        $this->addSql('CREATE INDEX IDX_AF05376C12469DE2 ON user_hidden_category (category_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE user_settings (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              value VARCHAR(255) DEFAULT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_5C844C5A76ED395 ON user_settings (user_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              comment
            ADD
              CONSTRAINT FK_9474526CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              comment
            ADD
              CONSTRAINT FK_9474526C4B89032C FOREIGN KEY (post_id) REFERENCES post (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              heart
            ADD
              CONSTRAINT FK_60ECC3E6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              heart
            ADD
              CONSTRAINT FK_60ECC3E64B89032C FOREIGN KEY (post_id) REFERENCES post (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              moderation_log
            ADD
              CONSTRAINT FK_7AE8684DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              notification
            ADD
              CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              notification
            ADD
              CONSTRAINT FK_BF5476CA4B89032C FOREIGN KEY (post_id) REFERENCES post (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              notification
            ADD
              CONSTRAINT FK_BF5476CAF8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              post
            ADD
              CONSTRAINT FK_5A8A6C8DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              post
            ADD
              CONSTRAINT FK_5A8A6C8D12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              post_attachment
            ADD
              CONSTRAINT FK_5A27D07A4B89032C FOREIGN KEY (post_id) REFERENCES post (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              post_attachment
            ADD
              CONSTRAINT FK_5A27D07AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              registration_question_answer
            ADD
              CONSTRAINT FK_58C2CB1B1E27F6BF FOREIGN KEY (question_id) REFERENCES registration_question (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              report
            ADD
              CONSTRAINT FK_C42F778471CE806 FOREIGN KEY (reported_by_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              report
            ADD
              CONSTRAINT FK_C42F77844B89032C FOREIGN KEY (post_id) REFERENCES post (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              report
            ADD
              CONSTRAINT FK_C42F7784F8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_freeze_log
            ADD
              CONSTRAINT FK_1FBF84DAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_hidden_category
            ADD
              CONSTRAINT FK_AF05376CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_hidden_category
            ADD
              CONSTRAINT FK_AF05376C12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_settings
            ADD
              CONSTRAINT FK_5C844C5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CA76ED395');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C4B89032C');
        $this->addSql('ALTER TABLE heart DROP CONSTRAINT FK_60ECC3E6A76ED395');
        $this->addSql('ALTER TABLE heart DROP CONSTRAINT FK_60ECC3E64B89032C');
        $this->addSql('ALTER TABLE moderation_log DROP CONSTRAINT FK_7AE8684DA76ED395');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA4B89032C');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAF8697D13');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8DA76ED395');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8D12469DE2');
        $this->addSql('ALTER TABLE post_attachment DROP CONSTRAINT FK_5A27D07A4B89032C');
        $this->addSql('ALTER TABLE post_attachment DROP CONSTRAINT FK_5A27D07AA76ED395');
        $this->addSql('ALTER TABLE registration_question_answer DROP CONSTRAINT FK_58C2CB1B1E27F6BF');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F778471CE806');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F77844B89032C');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784F8697D13');
        $this->addSql('ALTER TABLE user_freeze_log DROP CONSTRAINT FK_1FBF84DAA76ED395');
        $this->addSql('ALTER TABLE user_hidden_category DROP CONSTRAINT FK_AF05376CA76ED395');
        $this->addSql('ALTER TABLE user_hidden_category DROP CONSTRAINT FK_AF05376C12469DE2');
        $this->addSql('ALTER TABLE user_settings DROP CONSTRAINT FK_5C844C5A76ED395');
        $this->addSql('DROP TABLE announcement');
        $this->addSql('DROP TABLE blocked_email_address');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE heart');
        $this->addSql('DROP TABLE moderation_log');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE post');
        $this->addSql('DROP TABLE post_attachment');
        $this->addSql('DROP TABLE registration_question');
        $this->addSql('DROP TABLE registration_question_answer');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE sidebar_content');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_freeze_log');
        $this->addSql('DROP TABLE user_hidden_category');
        $this->addSql('DROP TABLE user_settings');
    }
}
