#!/bin/sh
set -e

chown root:www-data /var/www/uploads
chmod g+w /var/www/uploads

curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
curl -sS https://get.symfony.com/cli/installer | bash && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

composer install

npm install
npm run build

/usr/local/bin/php /var/www/html/bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
/usr/local/bin/php /var/www/html/bin/console cache:clear

if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

exec "$@"
