#!/bin/sh

source /etc/container_env

php /var/www/html/bin/console habitat:expire-moderation-logs
php /var/www/html/bin/console habitat:send-daily-digest-email
php /var/www/html/bin/console habitat:cleanup-attachments
